//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Health_Desktop_App.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EHealthContext : DbContext
    {
        public EHealthContext()
            : base("name=EHealthContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gambar> gambar { get; set; }
        public DbSet<jejaring_sosial> jejaring_sosial { get; set; }
        public DbSet<log_data> log_data { get; set; }
        public DbSet<obat> obat { get; set; }
        public DbSet<penyakit> penyakit { get; set; }
        public DbSet<user> user { get; set; }
    }
}
