//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Health_Desktop_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class obat
    {
        public obat()
        {
            this.penyakit = new HashSet<penyakit>();
        }
    
        public long id { get; set; }
        public string nama { get; set; }
        public string keterangan { get; set; }
        public string dosis { get; set; }
    
        public virtual ICollection<penyakit> penyakit { get; set; }
    }
}
