//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Health_Desktop_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.jejaring_sosial = new HashSet<jejaring_sosial>();
            this.user1 = new HashSet<user>();
            this.user2 = new HashSet<user>();
        }
    
        public long id { get; set; }
        public string nomor_sip { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string nama { get; set; }
        public string lokasi_penugasan { get; set; }
        public string no_telp { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<jejaring_sosial> jejaring_sosial { get; set; }
        public virtual ICollection<user> user1 { get; set; }
        public virtual ICollection<user> user2 { get; set; }
    }
}
